
How to bootstrap a Debian system on a SD card.
Tested on a Debian/amd64 host.

Applies to the Roboard.

!!
  Be warned that it is expected that the SD card is on /dev/sdb.
  If you have two hard drives, it is highly probable that /dev/sdb is your
  second hard drive
!!

* Partition the SD card
 * # parted /dev/sdb
 * Within parted,
   * mkpart (and answer ext3, 64s, 3072M)
   * mkpart (and answer linux-swap, 3072M, 3584M)
   * toggle 1 boot
   * quit

* Prepare/format partitions
 * # mke2fs -t ext3 /dev/sdb1
 * # tune2fs -c 0 -i 0 /dev/sdb1 
(this is quite important because it will prevent an unexpected fsck at
the wrong moment)
 * # mkswap /dev/sdb2

* Mount root file system
 * # mount /dev/sdb1 /mnt/roboard

* Bootstrap Debian system (requires installation of debootstrap)
 * # debootstrap --arch=i386 squeeze /mnt/roboard
(lasts quite long)
 * # mount -o bind /dev /mnt/roboard/dev
 * Edit /mnt/roboard/etc/fstab so that it contains

proc		/proc	proc	defaults		0	0
/dev/sda1	/	ext3	errors=remount-ro	0	1
/dev/sda2	none	swap	sw			0	0

 * Edit /mnt/roboard/etc/inittab and make sure there is a line
T0:23:respawn:/sbin/getty -L ttyS0 115200 vt100
 * # chroot /mnt/roboard
   chroot# mount /proc
   chroot# apt-get install linux-image-486
   chroot# apt-get install grub
   Edit /etc/default/grub and add the lines
GRUB_TERMINAL_INPUT=serial
GRUB_TERMINAL_OUTPUT=serial
   chroot# grub-install /dev/sdb
   chroot# umount /proc
   chroot# exit

 * # umount /mnt/roboard/dev
 * # umount /mnt/roboard

